"""v20_add_research_tables

Revision ID: b7e79684b9d2
Revises: 1796e6748184
Create Date: 2026-06-10 10:07:47.205342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e79684b9d2'
down_revision: Union[str, Sequence[str], None] = '1796e6748184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('reviewer_result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_exec_tenant_status', 'research_executions', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_research_executions_execution_id'), 'research_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_research_executions_status'), 'research_executions', ['status'], unique=False)
    op.create_index(op.f('ix_research_executions_tenant_id'), 'research_executions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_research_executions_user_id'), 'research_executions', ['user_id'], unique=False)
    op.create_table('research_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('citation', sa.String(length=2048), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['research_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_evidence_evidence_id'), 'research_evidence', ['evidence_id'], unique=True)
    op.create_index('ix_research_evidence_exec_task', 'research_evidence', ['execution_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_research_evidence_execution_id'), 'research_evidence', ['execution_id'], unique=False)
    op.create_index(op.f('ix_research_evidence_task_id'), 'research_evidence', ['task_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('evidence_map_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['research_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_report_exec', 'research_reports', ['execution_id'], unique=False)
    op.create_index(op.f('ix_research_reports_execution_id'), 'research_reports', ['execution_id'], unique=False)
    op.create_index(op.f('ix_research_reports_report_id'), 'research_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_workflow_artifacts_execution_id'), 'workflow_artifacts', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_tenant_id'), 'workflow_definitions', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_wf_exec_execution_id'), table_name='workflow_executions')
    op.create_index('ix_wf_exec_execution_id', 'workflow_executions', ['execution_id'], unique=False)
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=False)
    op.drop_index('ix_wf_exec_execution_id', table_name='workflow_executions')
    op.create_index(op.f('ix_wf_exec_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    op.drop_index(op.f('ix_workflow_definitions_tenant_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_artifacts_execution_id'), table_name='workflow_artifacts')
    op.drop_index(op.f('ix_research_reports_report_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_execution_id'), table_name='research_reports')
    op.drop_index('ix_research_report_exec', table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_evidence_task_id'), table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_execution_id'), table_name='research_evidence')
    op.drop_index('ix_research_evidence_exec_task', table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_evidence_id'), table_name='research_evidence')
    op.drop_table('research_evidence')
    op.drop_index(op.f('ix_research_executions_user_id'), table_name='research_executions')
    op.drop_index(op.f('ix_research_executions_tenant_id'), table_name='research_executions')
    op.drop_index(op.f('ix_research_executions_status'), table_name='research_executions')
    op.drop_index(op.f('ix_research_executions_execution_id'), table_name='research_executions')
    op.drop_index('ix_research_exec_tenant_status', table_name='research_executions')
    op.drop_table('research_executions')
    # ### end Alembic commands ###
